## 00. PyTorch fundamentals

Resource nootebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


## Introductin to Tensors

### Creating tensors

PyTorch tensors created using `torch.Tensor()` Look at the documentattion

Torch tensor: https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim  # .ndim gives dimension

0

In [ ]:
## get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[[1, 2, 3],
                        [1, 4, 5],
                        [8, 2, 7],
                        [1, 2, 3],
                        [1, 4, 5],
                        [8, 2, 7]],
                       [[1, 2, 3],
                        [1, 4, 5],
                        [8, 2, 7],
                        [1, 2, 3],
                        [1, 4, 5],
                        [8, 2, 7]]]])
TENSOR

tensor([[[[1, 2, 3],
          [1, 4, 5],
          [8, 2, 7],
          [1, 2, 3],
          [1, 4, 5],
          [8, 2, 7]],

         [[1, 2, 3],
          [1, 4, 5],
          [8, 2, 7],
          [1, 2, 3],
          [1, 4, 5],
          [8, 2, 7]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 2, 6, 3])

In [ ]:
TENSOR[0]

tensor([[[1, 2, 3],
         [1, 4, 5],
         [8, 2, 7],
         [1, 2, 3],
         [1, 4, 5],
         [8, 2, 7]],

        [[1, 2, 3],
         [1, 4, 5],
         [8, 2, 7],
         [1, 2, 3],
         [1, 4, 5],
         [8, 2, 7]]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks lean is that they start with tensors full of random numbers and then adjust those random numers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update numbers`

Torch random tensor: https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4148, 0.7868, 0.0089, 0.6815],
        [0.4983, 0.3475, 0.0689, 0.0363],
        [0.5765, 0.2492, 0.7493, 0.5411]])

In [ ]:
# Create a random tneosr with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(3, 224, 224)) # height, width, colour channel (R, G ,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor off all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange(=)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 bif errors you will run into PyTorch & deep learing:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g float32 or float16)
                               device=None, # What device it tenosr on
                               requires_grad=False # Whether or not to track gradiants with tensor operations.
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Geting information from tensors (Tensor atributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5922, 0.6121, 0.4841, 0.6166],
        [0.4259, 0.4116, 0.4948, 0.1494],
        [0.6784, 0.8001, 0.8466, 0.5429]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5922, 0.6121, 0.4841, 0.6166],
        [0.4259, 0.4116, 0.4948, 0.1494],
        [0.6784, 0.8001, 0.8466, 0.5429]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor opeartions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add ten to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing multiĺication needs to satisfy:
1. The **inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.9143, 0.7504],
        [0.8529, 0.7223]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplicatoin by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.77 ms, sys: 904 µs, total: 2.67 ms
Wall time: 2.7 ms


In [ ]:
%%time
value = torch.matmul(tensor, tensor)
print(value)

tensor(14)
CPU times: user 2.69 ms, sys: 0 ns, total: 2.69 ms
Wall time: 2.7 ms


### One of the most common erros in deep leraning: shape errors

In [ ]:
# Shapes for matrix multiĺication
tensor_A = torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul (it's alias for matmul)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor agreagation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean -note: the torch.mean() funciton require a tensor float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
## Finding the tpoistion with maximal value and returns its index

torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
## Finding the tpoistion with minimal value and returns its index
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view id the input with dimensions  permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5 # : refers to the first element
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions of a tensor
print(f"Previus tensor: {x_reshaped}")
print(f"Previus shape: {x_reshaped.shape}")

# Remove extra dimensions from x
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previus tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previus shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"previus target: {x_squeezed}")
print(f"previus shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


previus target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previus shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# Torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permutethe original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"previus shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

previus shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracked (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (dim=2)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all value of 0th and 1st dimensions but only index 1 of de 2nd dimension
print(x[:, :, 1])

tensor([[2, 5, 8]])


In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[:, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


## Pytorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`
#

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch reflect's numpy's  default datatype float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([ 9., 13., 17., 21., 25., 29., 33.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3173, 0.1232, 0.3284, 0.8061],
        [0.3150, 0.2917, 0.6627, 0.5793],
        [0.9300, 0.2027, 0.9549, 0.0950]])
tensor([[0.6188, 0.2709, 0.0951, 0.2224],
        [0.2299, 0.7177, 0.5925, 0.3229],
        [0.0102, 0.3568, 0.7235, 0.5257]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible rensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility

* https://pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed



## Runing tensors and PyTorch objects on the  GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computing on the cloud and acces them

In [ ]:
!nvidia-smi

Wed Aug  7 23:03:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU acces with PyTorch

In [ ]:
# Check for GPU acces with PyTorch

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if avilable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')